#!/usr/bin/env bash
# Install local git hooks for the unified clinical workflow sample.
# Run once after cloning: `bash scripts/install-hooks.sh`

set -e

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"

if [ ! -d "$HOOKS_DIR" ]; then
    echo "ERROR: $HOOKS_DIR does not exist. Are you in a git repo?"
    exit 1
fi

# Pre-commit hook
cat > "$HOOKS_DIR/pre-commit" << 'HOOKEOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh
exec "$(git rev-parse --show-toplevel)/scripts/pre-commit-security-check.sh"
HOOKEOF
chmod +x "$HOOKS_DIR/pre-commit"

echo "✓ Installed pre-commit hook at $HOOKS_DIR/pre-commit"
echo "  Run \`bash scripts/pre-commit-security-check.sh\` manually any time."
